### ISSUE TITLE
Input icon  it does not work

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [heyui/heyui#13]
![screenshot_11](https://user-images.githubusercontent.com/31676496/42730538-41a5705c-87bc-11e8-9897-29b8010887ac.png)

**Comment by vvpvvp** [comment]
you mean it should like this?
![image](https://user-images.githubusercontent.com/7303371/42730588-c09f4a7c-882a-11e8-9fdc-54888dacab40.png)

I will fixed it next version.

or you could add a style by yourself.

``` css

.h-input>input{
  padding-right: 25px;
}
```
