### ISSUE TITLE
Select控件选择后文字向右多偏移了5px

### ISSUE THREAD

**Issue by zhangkx666** [heyui/heyui#306]
**描述这个bug**
Select控件选择后文字向右多偏移了5px

**重现步骤**
步骤:  
1. Select从没有选中状态变为选中状态时

**期望行为**
Select选择后，文字的位置应该和选择之前的placeholder位置一致

**截图**
![image](https://user-images.githubusercontent.com/13268310/91650831-35c15980-eab7-11ea-8737-098c394a7012.png)

**请完整的描述以下信息**
 - 操作系统:  win10
 - 浏览器: Chrome 85.0.4183.83（正式版本）（32 位）

**补充信息**
原因我大致看了下，
没选择之前dom如下：
```html
<div class="h-select-placeholder">select</div>
```

选择后dom如下：
```html
<div class="h-select-value-single">
   <div class="h-select-value-single">demo1</div>
</div>
```
而h-select-value-single的样式padding-left: 5px，所以嵌套了两层后选中之后padding-left就叠加到了10px。
这里应该是多嵌套了一层h-select-value-single吧。
为了消除这个影响，我只好自己添加了一个css
```css
.h-select-value-single {
  .h-select-value-single {
    padding-left: 0;
  }
}
```
别告诉我亲就是这样设计的，哈哈。
