### ISSUE TITLE
a标签样式中的!important可以拿掉吗

### ISSUE THREAD

**Issue by zhangkx666** [heyui/heyui#307]
a标签样式的hover和active带了!important，导致我所有的自定义css必须也带important，有些场景下很难控制。感觉通用样式不需要带important。因为我多主题的实现方式并不是直接加载不同主题的css文件，所以为了覆盖这些带important的规则，很难受 😂

```css
.h-func-link() {
  color: @link-color;
  cursor: pointer;
  text-decoration: none;
  outline: none;
  transition: color @transition-time ease;
  &:hover {
    color: darken(@link-color, 10%) !important;
  }
  &:active {
    color: darken(@link-color, 20%) !important;
  }
  &:active, &:hover{
    outline: 0;
    text-decoration: none;
  }
  &[disabled] {
    color: @disabled-color !important;
    cursor: default;
  }
}
```
